DoAnCoSoPhanModel-DB/Models/Feedbacks.cs
using System.ComponentModel.DataAnnotations.Schema;

using System.ComponentModel.DataAnnotations;

namespace DoAnCoSoPhanModel_DB.Models
{
    public class Feedbacks
    {
        public Guid Id { get; set; }
        [Required]
        public string title { get; set; }
        [Required]
        public string content { get; set; }
        public Student? student { get; set; }
    }
}

DoAnCoSoPhanModel-DB/Controllers/FeedbackController.cs
using DoAnCoSoPhanModel_DB.Models;
using DoAnCoSoPhanModel_DB.Repositories;
using Microsoft.AspNetCore.Mvc;

namespace DoAnCoSoPhanModel_DB.Controllers
{
    public class FeedbackController : Controller
    {
        private readonly IFeedBacksRepository _feedBacksRepository;

        public FeedbackController(IFeedBacksRepository feedBacksRepository)
        {
            _feedBacksRepository = feedBacksRepository;
        }
        public async Task<IActionResult> IndexFeedBack()
        {
            var feedback = await _feedBacksRepository.GetAllAsync();
            return View(feedback);
        }

        public async Task<IActionResult> DetailsFeedback(Guid id)
        {
            var feedbacks = await _feedBacksRepository.GetByIdAsync(id);
            if (feedbacks == null)
            {
                return NotFound();
            }
            return View(feedbacks);
        }

        public async Task<IActionResult> CreateFeedback()
        {
            var feedbacks = await _feedBacksRepository.GetAllAsync();

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> CreateFeedback(Feedbacks feedbacks)
        {
            if (ModelState.IsValid)
            {
                await _feedBacksRepository.AddAsync(feedbacks);
                return RedirectToAction(nameof(IndexFeedBack));
            }
            // Nếu ModelState không hợp lệ, hiển thị form với dữ liệu đã nhập

            return View(feedbacks);
        }

        public async Task<IActionResult> EditFeedback(Guid id)
        {
            var feedbacks = await _feedBacksRepository.GetByIdAsync(id);
            if (feedbacks == null)
            {
                return NotFound();
            }
            return View(feedbacks);
        }

        [HttpPost]
        public async Task<IActionResult> EditFeedback(Guid id, Feedbacks fb)
        {
            var existingFb = await _feedBacksRepository.GetByIdAsync(id);
            if (id != fb.Id)
            {
                return NotFound();
            }
            if (ModelState.IsValid)
            {
                existingFb.title = fb.title;
                existingFb.content = fb.content;

                await _feedBacksRepository.UpdateAsync(existingFb);
                return RedirectToAction(nameof(IndexFeedBack));
            }

            return View(fb);
        }


    }
}

DoAnCoSoPhanModel-DB/Views/Feedback/CreateFeedback.cshtml
@model DoAnCoSoPhanModel_DB.Models.Feedbacks

@{
    ViewData["Title"] = "CreateFeedback";
}

<h1>CreateFeedback</h1>

<h4>Feedbacks</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="CreateFeedback">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="title" class="control-label">Tiêu đề</label>
                <input asp-for="title" class="form-control" />
                <span asp-validation-for="title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="content" class="control-label">Nội dung</label>
                @* <input asp-for="content" class="form-control" /> *@
                <textarea id="tiny" asp-for="content" class="form-control"></textarea>
                <span asp-validation-for="content" class="text-danger"></span>
            </div>
            <hr />
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="IndexFeedback">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

DoAnCoSoPhanModel-DB/Views/Feedback/DetailsFeedback.cshtml
@model DoAnCoSoPhanModel_DB.Models.Feedbacks

@{
    ViewData["Title"] = "DetailsFeedback";
}

<div class="container">
    <h1>DetailsFeedback</h1>
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">Feedbacks</h4>
            <hr />
            <dl class="row">
                <dt class="col-sm-2">@Html.DisplayNameFor(model => model.title)</dt>
                <dd class="col-sm-10">@Html.DisplayFor(model => model.title)</dd>

                <dt class="col-sm-2">@Html.DisplayNameFor(model => model.content)</dt>
                <dd class="col-sm-10">
                    @if (Model.content.Length > 100)
                    {
                        <p>@Html.DisplayFor(model => model.content)</p>
                    }
                    else
                    {
                        @Html.DisplayFor(model => model.content)
                    }
                </dd>
            </dl>
        </div>
    </div>
    <div class="mt-3">
        <a asp-action="EditFeedback" asp-route-id="@Model?.Id" class="btn btn-primary">Edit</a>
        <a asp-action="IndexFeedback" class="btn btn-secondary">Back to List</a>
    </div>
</div>

DoAnCoSoPhanModel-DB/Views/Feedback/EditFeedback.cshtml
@model DoAnCoSoPhanModel_DB.Models.Feedbacks

@{
    ViewData["Title"] = "EditFeedback";
}

<div class="container px-4">
    <h2 class="mt-3 mb-3 ml-3">Chỉnh sửa Phản hồi</h2>
    <hr />
    <div class="row mb-4">
        <div class="col-md-10 offset-md-1">
            <form asp-action="EditFeedback" method="post" enctype="multipart/form-data">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <input type="hidden" asp-for="Id" />
                <div class="form-group mb-2">
                    <label asp-for="title" class="control-label">Tiêu Đề</label>
                    <input asp-for="title" class="form-control" />
                    <span asp-validation-for="title" class="text-danger"></span>
                </div>
                <div class="form-group mb-2">
                    <label asp-for="content" class="control-label">Nội dung</label>
                    <input asp-for="content" class="form-control" />
                    <span asp-validation-for="content" class="text-danger"></span>
                </div>
                <div class="form-group mt-3">
                    <button type="submit" class="btn btn-lg btn-primary">Cập nhật</button>
                </div>
            </form>
        </div>
    </div>

    <div>
        <a asp-action="IndexFeedback" class="btn btn-secondary">Quay lại danh sách</a>
    </div>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

DoAnCoSoPhanModel-DB/Views/Feedback/IndexFeedBack.cshtml
@model List<DoAnCoSoPhanModel_DB.Models.Feedbacks>
@{
    ViewData["Title"] = "Phản Hồi Của HS";
}
<!-- Header Start -->
<div class="container-fluid bg-primary py-5 mb-5 page-header">
    <div class="container py-5">
        <div class="row justify-content-center">
            <div class="col-lg-10 text-center">
                <h1 class="display-3 text-white animated slideInDown">Testimonial</h1>
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb justify-content-center">
                        <li class="breadcrumb-item"><a class="text-white" href="#">Home</a></li>
                        <li class="breadcrumb-item"><a class="text-white" href="#">Pages</a></li>
                        <li class="breadcrumb-item text-white active" aria-current="page">Testimonial</li>
                    </ol>
                </nav>
            </div>
        </div>
    </div>
</div>
<!-- Header End -->
<!-- Testimonial Start -->
<div class="container-xxl py-5 wow fadeInUp" data-wow-delay="0.1s">
    <div class="container">
        <div class="text-center">
            <h6 class="section-title bg-white text-center text-primary px-3">Testimonial</h6>
            <h1 class="mb-5">Phản hồi của Các em Học Sinh!</h1>
        </div>
        <div class="owl-carousel testimonial-carousel position-relative">
            @foreach (var feedback in Model)
            {
                <div class="testimonial-item text-center">
                    <img class="border rounded-circle p-2 mx-auto mb-3" src="/Theme/img/testimonial-4.jpg" style="width: 80px; height: 80px;">
                    <h5 class="mb-0">Tên Tạm</h5>
                    <p>@feedback.title</p>
                    <div class="testimonial-text bg-light text-center p-4">
                        @if (feedback.content.Length > 40) // Kiểm tra độ dài của nội dung
                        {
                            <p class="mb-0"><a href="@Url.Action("DetailsFeedback", "Feedback", new { id = feedback.Id })">@feedback.content.Substring(0, 40)...</a></p> <!-- Nếu quá dài, chỉ hiển thị 100 ký tự đầu tiên -->
                        }
                        else
                        {
                            <p class="mb-0"><a href="@Url.Action("DetailsFeedback", "Feedback", new { id = feedback.Id })">@feedback.content</a></p> <!-- Nếu không, hiển thị toàn bộ nội dung -->
                        }
                    </div>
                </div>
            }
        </div>
    </div>
    <div>
        <a asp-action="CreateFeedback" class="btn btn-success">Đăng phản hồi</a>
    </div>
@*     <hr />
    <div>
        <a asp-action="GetAllFeedbacks" class="btn btn-primary">Xem Nhiều</a>
    </div> *@
</div>

<!-- Testimonial End -->