DoAnCoSoPhanModel-DB/Models/News.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DoAnCoSoPhanModel_DB.Models
{
    public class News
    {
        public Guid Id { get; set; }

        [Required]
        public string Title { get; set; }
        [Required]
        public string Content { get; set; }

        public string? ImageUrl { get; set; }

        public DateTime time_create { get; set; }
        public DateTime time_update { get; set; }
        
        public virtual ApplicationUser? applicationUser { get; set; }

    }
}

DoAnCoSoPhanModel-DB/Controllers/NewsController.cs
using DoAnCoSoPhanModel_DB.Models;
using DoAnCoSoPhanModel_DB.Repositories;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace DoAnCoSoPhanModel_DB.Controllers
{
    public class NewsController : Controller
    {
        private readonly INewsRepository _newsRepository;

        public NewsController(INewsRepository newsRepository)
        {
            _newsRepository = newsRepository;
        }
        public async Task<IActionResult> IndexNews()
        {
            var news = await _newsRepository.GetAllAsync();
            ViewBag.NumberOfFB = news.Count();
            return View(news);
        }

        public async Task<IActionResult> NguoiDungNews()
        {
            var gv = await _newsRepository.GetAllAsync();
            
            return View(gv);
        }


        public async Task<IActionResult> CreateNews()
        {
            var news = await _newsRepository.GetAllAsync();
            return View();
        }


        [HttpPost]
        public async Task<IActionResult> CreateNews(News news, IFormFile ImageUrl)
        {
            if (ModelState.IsValid)
            {
                if (ImageUrl != null)
                {
                    // Lưu hình ảnh đại diện
                    news.ImageUrl = await SaveImage(ImageUrl);
                }
                news.time_create = DateTime.Now;
                await _newsRepository.AddAsync(news);
                return RedirectToAction(nameof(NguoiDungNews));
            }

            return View(news);
        }

        private async Task<string> SaveImage(IFormFile ImageUrl)
        {
            var savePath = Path.Combine("wwwroot/New/images", ImageUrl.FileName); // Thay đổi đường dẫn theo cấu hình của bạn
            using (var fileStream = new FileStream(savePath, FileMode.Create))
            {
                await ImageUrl.CopyToAsync(fileStream);
            }
            return "/New/images/" + ImageUrl.FileName; // Trả về đường dẫn tương đối
        }

        public async Task<IActionResult> DetailsNews(Guid id)
        {
            var news = await _newsRepository.GetByIdAsync(id);
            if (news == null)
            {
                return NotFound();
            }
            return View(news);
        }


        public async Task<IActionResult> EditNews(Guid id)
        {
            var news = await _newsRepository.GetByIdAsync(id);
            if (news == null)
            {
                return NotFound();
            }
            return View(news);
        }
        // Process the product update
        [HttpPost]
        public async Task<IActionResult> Edit(Guid id, News news, IFormFile ImageUrl)
        {
            ModelState.Remove("ImageUrl");
            var existingNews = await _newsRepository.GetByIdAsync(id);
            if (id != news.Id)
            {
                return NotFound();
            }
            if (ModelState.IsValid)
            {
                if (ImageUrl != null)
                {
                    // Lưu hình ảnh đại diện
                    news.ImageUrl = await SaveImage(ImageUrl);
                }
                else
                {
                    news.ImageUrl = existingNews.ImageUrl;
                }
                existingNews.Title = news.Title;
                existingNews.Content = news.Content;

                existingNews.time_update = DateTime.Now;

                existingNews.ImageUrl = news.ImageUrl;
                existingNews.time_create = existingNews.time_create;
                await _newsRepository.UpdateAsync(existingNews);
                return RedirectToAction(nameof(IndexNews));
            }

            return View(news);
        }

        public async Task<IActionResult> DeleteNews(Guid id)
        {
            var news = await _newsRepository.GetByIdAsync(id);
            if (news == null)
            {
                return NotFound();
            }
            return View(news);
        }
        // Xử lý xóa sản phẩm
        [HttpPost, ActionName("DeleteNews")]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            await _newsRepository.DeleteAsync(id);
            return RedirectToAction(nameof(IndexNews));
        }
    }
}

DoAnCoSoPhanModel-DB/Views/News/DetailsNews.cshtml
@model DoAnCoSoPhanModel_DB.Models.News

@{
    ViewData["Title"] = "Details";
}

<div class="container">
    <h1>Details</h1>
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">News</h4>
            <hr />
            <dl class="row">
                <dt class="col-sm-2">Title</dt>
                <dd class="col-sm-10">@Html.DisplayFor(model => model.Title)</dd>
                
                <dt class="col-sm-2">Image</dt>
                <dd class="col-sm-10">
                    @if (!string.IsNullOrEmpty(Model.ImageUrl))
                    {
                        <img src="@Model.ImageUrl" class="img-fluid" alt="News Image" width="800px" height="auto">
                    }
                    else
                    {
                        <p>No image available</p>
                    }
                </dd>

                <dt class="col-sm-2">Content</dt>
                <dd class="col-sm-10">
                    @if (Model.Content.Length > 100)
                    {
                        <p>@Html.DisplayFor(model => model.Content)</p>
                    }
                    else
                    {
                        @Html.DisplayFor(model => model.Content)
                    }
                </dd>

                <dt class="col-sm-2">Created Time</dt>
                <dd class="col-sm-10">@Html.DisplayFor(model => model.time_create)</dd>
                <dt class="col-sm-2">Updated Time</dt>
                <dd class="col-sm-10">@Html.DisplayFor(model => model.time_update)</dd>
            </dl>
        </div>
    </div>
    <div class="mt-3">
        @* <a asp-action="EditNews" asp-route-id="@Model?.Id" class="btn btn-primary">Edit</a> *@
        <a asp-action="NguoiDungNews" class="btn btn-secondary">Back to List</a>
    </div>
</div>

DoAnCoSoPhanModel-DB/Views/News/IndexNews.cshtml
@model IEnumerable<DoAnCoSoPhanModel_DB.Models.News>

@{
    ViewData["Title"] = "IndexNews";

}

<div class="container-fluid px-4">
    <!-- Sử dụng container-fluid để làm cho chiều ngang to hơn -->
    <h2 class="mt-3 mb-3 ml-3">Danh sách Tin Tức</h2>
    <hr />

    <div class="row mb-4">
        <div class="col-md-12">
            <!-- Sử dụng col-md-12 để làm cho bảng chiều ngang đầy đủ trên các thiết bị lớn -->
            <table class="table">
                <thead>
                    <tr>
                        <th>Tiêu Đề</th>
                        <th>Nội dung</th>
                        <th>Ảnh nền</th>
                        <th>Thời gian đăng</th>
                        <th>Thời gian cập nhật</th>
                        @* <th>Actions</th> *@
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td style="width=50px">@item.Title</td>
                            <td>
                                @if (item.Content.Length > 60)
                                {
                                    <span title="@item.Content">@item.Content.Substring(0, 60)...</span>
                                }
                                else
                                {
                                    @item.Content
                                }
                            </td>
                            <td>
                                @if (item.ImageUrl != null)
                                {
                                    <img src="@item.ImageUrl" width="150px" height="auto" />
                                }
                            </td>
                            <td>@item.time_create</td>
                            <td>@item.time_update</td>
                            @* <td style="max-width=200px">
                                <a asp-action="DetailsNews" asp-route-id="@item.Id" class="btn btn-info">Xem chi tiết</a>
                                <a asp-action="DeleteNews" asp-route-id="@item.Id" class="btn btn-danger">Xoá</a>
                                <a asp-action="EditNews" asp-route-id="@item.Id" class="btn btn-warning">Sửa</a>
                            </td> *@
                        </tr>
                    }
                </tbody>
            </table>
        </div>
    </div>

@*     <div>
        <a asp-action="CreateNews" class="btn btn-success">Tạo Tin Tức</a>
    </div> *@
    <hr />
    <div>
        <a asp-action="NguoiDungNews" class="btn btn-primary">Trở Lại</a>
    </div>
</div>


@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

DoAnCoSoPhanModel-DB/Views/News/NguoiDungNews.cshtml
@model List<DoAnCoSoPhanModel_DB.Models.News>
@{
    ViewData["Title"] = "Tin Tức";
}


<!-- Team Start -->
<div class="container-xxl py-5">
    <div class="container">
        <div class="text-center wow fadeInUp" data-wow-delay="0.1s">
            <h6 class="section-title bg-white text-center text-primary px-3">NEWS</h6>
            <h1 class="mb-5">TIN TỨC</h1>
        </div>
        <div class="row g-4">
            @if (Model != null)
            {
                @foreach (var news in Model)
                {
                    <div class="col-lg-3 col-md-6 wow fadeInUp" data-wow-delay="0.1s">
                        <div class="team-item bg-light">
                            <div class="overflow-hidden">
                                <img class="img-fluid" style="width: 100%; height: 180px" src="@news.ImageUrl" alt="@news.Title">
                            </div>
                            
                            <div class="text-center p-4">
                                <h5 class="mb-0"><a href="@Url.Action("DetailsNews", "News", new { id = news.Id })">@news.Title</a></h5>
                                <small>@news.time_create</small>
                            </div>
                        </div>
                    </div>
                }
            }
        </div>
    </div>
    <hr />
@*     <div>
        <a asp-action="CreateNews" class="btn btn-success">Thêm Tin Tức</a>
    </div> *@
    <hr />
    <div>
        <a asp-action="IndexNews" class="btn btn-primary">Xem Danh Sách Tin Tức</a>
    </div>
</div>
<!-- Team End -->