DoAnCoSoPhanModel-DB/Models/Documents.cs
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace DoAnCoSoPhanModel_DB.Models
{
    public class Documents
    {
        public Guid Id { get; set; }
        [Required]
        public string title { get; set; }
        [Required]
        public string Content { get; set; }

        public string? ImageUrl { get; set; }

        public String? files { get; set; }

        public String? videos { get; set; }

        public Subject? subject { get; set; }

        public Teacher? teacher { get; set; }
    }
}

DoAnCoSoPhanModel-DB/Controllers/DocumentController.cs
using DoAnCoSoPhanModel_DB.Models;
using DoAnCoSoPhanModel_DB.Repositories;
using Microsoft.AspNetCore.Mvc;

namespace DoAnCoSoPhanModel_DB.Controllers
{
    public class DocumentController : Controller
    {
        private readonly IDocumentsRepository _documentsRepository;

        public DocumentController(IDocumentsRepository documentsRepository)
        {
            _documentsRepository = documentsRepository;
        }

        public async Task<IActionResult> NguoiDungDocument()
        {
            var d = await _documentsRepository.GetAllAsync();

            return View(d);
        }

        public async Task<IActionResult> DetailsDocument(Guid id)
        {
            var d = await _documentsRepository.GetByIdAsync(id);
            if (d == null)
            {
                return NotFound();
            }
            return View(d);
        }
    }
}

DoAnCoSoPhanModel-DB/Views/Document/DetailsDocument.cshtml
@model DoAnCoSoPhanModel_DB.Models.Documents

@{
    ViewData["Title"] = "DetailsDocument";
}

<div class="container">
    <h1>DetailsDocument</h1>
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">Documents</h4>
            <hr />
            <dl class="row">
                <dt class="col-sm-2">@Html.DisplayNameFor(model => model.title)</dt>
                <dd class="col-sm-10">@Html.DisplayFor(model => model.title)</dd>

                <dt class="col-sm-2">@Html.DisplayNameFor(model => model.Content)</dt>
                <dd class="col-sm-10">
                    @Html.DisplayFor(model => model.Content)
                </dd>

                <dt class="col-sm-2">@Html.DisplayNameFor(model => model.files)</dt>
                <dd class="col-sm-10">
                    <embed src="@Model.files" type="application/pdf" width="100%" height="1000px" />
                </dd>

                <dt class="col-sm-2">@Html.DisplayNameFor(model => model.videos)</dt>
                <dd class="col-sm-10">
                    <iframe width="100%" height="500px" src="@Model.videos" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" referrerpolicy="strict-origin-when-cross-origin" allowfullscreen></iframe>
                </dd>
            </dl>
        </div>
    </div>
    <div class="mt-3">
        <a asp-action="EditDocument" asp-route-id="@Model?.Id" class="btn btn-primary">Edit</a>
        <a asp-action="IndexDocument" class="btn btn-secondary">Back to List</a>
    </div>
</div>

DoAnCoSoPhanModel-DB/Views/Document/NguoiDungDocument.cshtml
@model List<DoAnCoSoPhanModel_DB.Models.Documents>

@{
    ViewData["Title"] = "NguoiDungDocument";
}

<div class="container-xxl py-5">
    <div class="container">
        <div class="text-center wow fadeInUp" data-wow-delay="0.1s">
            <h6 class="section-title bg-white text-center text-primary px-3">DOCUMENT</h6>
            <h1 class="mb-5">TÀI LIỆU</h1>
        </div>
        <div class="row g-4">
            @if (Model != null)
            {
                @foreach (var document in Model)
                {
                    <div class="col-lg-3 col-md-6 wow fadeInUp" data-wow-delay="0.1s">
                        <div class="team-item bg-light">
                            <div class="overflow-hidden">
                                <img class="img-fluid" style="width: 100%; height: 180px" src="@document.ImageUrl" alt="@document.title">
                            </div>

                            <div class="text-center p-4">
                                <h5 class="mb-0"><a href="@Url.Action("DetailsDocument", "Document", new { id = document.Id })">@document.title</a></h5>
                                <small>@document.Content</small>
                            </div>
                        </div>
                    </div>
                }
            }
        </div>
    </div>
    <hr />
@*     <div>
        <a asp-action="CreateDocument" class="btn btn-success">Thêm Tài Liệu</a>
    </div>
    <hr />
    <div>
        <a asp-action="IndexDocument" class="btn btn-primary">Xem Danh Sách Tài Liệu</a>
    </div> *@
</div>