DoAnCoSoPhanModel-DB/Controllers/CacMonHocController.cs
using DoAnCoSoPhanModel_DB.Models;
using DoAnCoSoPhanModel_DB.Repositories;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace DoAnCoSoPhanModel_DB.Controllers
{
    public class CacMonHocController : Controller
    {
        private readonly ISubjectRepository _subjectRepository;
        private readonly IDocumentsRepository _documentsRepository;

        public CacMonHocController(ISubjectRepository subjectRepository, IDocumentsRepository documentsRepository)
        {
            _subjectRepository = subjectRepository;
            _documentsRepository = documentsRepository;
        }

        public async Task<IActionResult> NguoiDungSubject()
        {
            var gv = await _subjectRepository.GetAllAsync();

            return View(gv);
        }
        public async Task<IActionResult> DetailsSubject(Guid id)
        {
            var subject = await _subjectRepository.GetByIdAsync(id);
            if (subject == null)
            {
                return NotFound();
            }
            return View(subject);
        }

    }
}

DoAnCoSoPhanModel-DB/Views/CacMonHoc/DetailsSubject.cshtml
@model DoAnCoSoPhanModel_DB.Models.Subject

@{
    ViewData["Title"] = "DetailsSubject";
}

<div class="container">
    <h1>Details</h1>
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">News</h4>
            <hr />
            <dl class="row">
                <dt class="col-sm-2">Title</dt>
                <dd class="col-sm-10">@Html.DisplayFor(model => model.Name)</dd>

                <dt class="col-sm-2">Image</dt>
                <dd class="col-sm-10">
                    @if (!string.IsNullOrEmpty(Model.ImageUrl))
                    {
                        <img src="@Model.ImageUrl" class="img-fluid" alt="News Image" width="150px">
                    }
                    else
                    {
                        <p>No image available</p>
                    }
                </dd>

                <dt class="col-sm-2">Miêu Tả</dt>
                <dd class="col-sm-10">
                    @if (Model.Description.Length > 100)
                    {
                        <p>@Html.DisplayFor(model => model.Description)</p>
                    }
                    else
                    {
                        @Html.DisplayFor(model => model.Description)
                    }
                </dd>

                <dt class="col-sm-2">Tài Liệu</dt>
                <dd class="col-sm-10">@Html.DisplayFor(model => model.Documents)</dd>
            </dl>
        </div>
    </div>
    <div class="mt-3">
        <a asp-action="EditSubject" asp-route-id="@Model?.Id" class="btn btn-primary">Edit</a>
        <a asp-action="IndexCacMonHoc" class="btn btn-secondary">Back to List</a>
    </div>
</div>

DoAnCoSoPhanModel-DB/Views/CacMonHoc/NguoiDungSubject.cshtml
@model List<DoAnCoSoPhanModel_DB.Models.Subject>
@{
    ViewData["Title"] = "Các Môn Học";
}


<!-- Team Start -->
<div class="container-xxl py-5">
    <div class="container">
        <div class="text-center wow fadeInUp" data-wow-delay="0.1s">
            <h6 class="section-title bg-white text-center text-primary px-3">HỌC BÀI</h6>
            <h1 class="mb-5">DANH SÁCH CÁC MÔN HỌC</h1>
        </div>
        <div class="row g-4">
            @if (Model != null)
            {
                @foreach (var subject in Model)
                {
                    <div class="col-lg-3 col-md-6 wow fadeInUp" data-wow-delay="0.1s">
                        <div class="team-item bg-light">
                            <div class="overflow-hidden">
                                <img class="img-fluid" style="width: 100%; height: 180px" src="@subject.ImageUrl" alt="@subject.Name">
                            </div>

                            <div class="text-center p-4">
                                <h5 class="mb-0"><a href="@Url.Action("DetailsSubject", "CacMonHoc", new { id = subject.Id })">@subject.Name</a></h5>
                                <small>@subject.Description</small>
                            </div>
                        </div>
                    </div>
                }
            }
        </div>
    </div>
    <hr />
@*     <div>
        <a asp-action="CreateSubject" class="btn btn-success">Thêm Môn Học</a>
    </div> *@
  @*   <hr />
    <div>
        <a asp-action="IndexCacMonHoc" class="btn btn-primary">Xem Danh Sách Môn Học</a>
    </div> *@
</div>
<!-- Team End -->